name: Run tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cargo
        actions: actions/set-up-cargo@v2
        with:
          rust-version: stable
      - name: Install dependencies
        run: cargo build
      - name: Run tests
        run: cargo test